create table test1 (a int, b string, c int);
insert into test1 (a, b, c) values (1, 'test1 row 1', 2);
insert into test1 (a, b, c) values (3, 'test1 row 2', 4);
create table test2 (a int, b string, c int);
insert into test2 (a, b, c) values (1, 'test2 1', 1);
insert into test2 (a, b, c) values (2, 'test2 2', 2);
insert into test2 (a, b, c) values (4, 'test2 4', 4);
insert into test2 (a, b, c) values (5, 'test2 5', 5);
insert into test2 (a, b, c) values (6, 'test2 6', 6);
insert into test2 (a, b, c) values (7, 'test2 7', 7);
insert into test2 (a, b, c) values (8, 'test2 8', 8);
insert into test2 (a, b, c) values (9, 'test2 9', 9);
insert into test2 (a, b, c) values (7, 'test2 7', 7);
insert into test2 (a, b, c) values (6, 'test2 6', 6);
insert into test2 (a, b, c) values (5, 'test2 5', 5);
insert into test2 (a, b, c) values (4, 'test2 4', 4);
insert into test2 (a, b, c) values (3, 'test2 3', 3);
insert into test2 (a, b, c) values (2, 'test2 2', 2);
insert into test2 (a, b, c) values (1, 'test2 1', 1);
select b from test1;
select a, c from test2;
select a, b, c from test2 where a == 7;