create table test1 (a int, b string, c int);
insert into test1 (a, b, c) values (1, 'test1 row 1', 2);
insert into test1 (a, b, c) values (3, 'test1 row 2', 4);
select b from test1;
select a, c from test1;
create table test2 (a int, b string, c int);
insert into test2 (a, b, c) values (1, 'one', 1);
insert into test2 (a, b, c) values (2, 'two', 2);
insert into test2 (a, b, c) values (2, 'two 2', 2);
insert into test2 (a, b, c) values (3, 'three', 3);
insert into test2 (a, b, c) values (3, 'three 2', 3);
insert into test2 (a, b, c) values (3, 'three 3', 3);
insert into test2 (a, b, c) values (4, 'four', 4);
insert into test2 (a, b, c) values (4, 'four 2', 4);
insert into test2 (a, b, c) values (4, 'four 3', 4);
insert into test2 (a, b, c) values (4, 'four 4', 4);
insert into test2 (a, b, c) values (5, 'five', 5);
insert into test2 (a, b, c) values (5, 'five 2', 5);
insert into test2 (a, b, c) values (5, 'five 3', 5);
insert into test2 (a, b, c) values (5, 'five 4', 5);
insert into test2 (a, b, c) values (5, 'five 5', 5);
insert into test2 (a, b, c) values (6, 'six', 6);
insert into test2 (a, b, c) values (6, 'six 2', 6);
insert into test2 (a, b, c) values (6, 'six 3', 6);
insert into test2 (a, b, c) values (6, 'six 4', 6);
insert into test2 (a, b, c) values (6, 'six 5', 6);
insert into test2 (a, b, c) values (6, 'six 6', 6);
insert into test2 (a, b, c) values (7, 'seven', 7);
insert into test2 (a, b, c) values (7, 'seven 2', 7);
insert into test2 (a, b, c) values (7, 'seven 3', 7);
insert into test2 (a, b, c) values (7, 'seven 4', 7);
insert into test2 (a, b, c) values (7, 'seven 5', 7);
insert into test2 (a, b, c) values (7, 'seven 6', 7);
insert into test2 (a, b, c) values (7, 'seven 7', 7);
insert into test2 (a, b, c) values (8, 'eight', 8);
insert into test2 (a, b, c) values (8, 'eight 2', 8);
insert into test2 (a, b, c) values (8, 'eight 3', 8);
insert into test2 (a, b, c) values (8, 'eight 4', 8);
insert into test2 (a, b, c) values (8, 'eight 5', 8);
insert into test2 (a, b, c) values (8, 'eight 6', 8);
insert into test2 (a, b, c) values (8, 'eight 7', 8);
insert into test2 (a, b, c) values (8, 'eight 8', 8);
select a, b, c from test2 where a == 5;
select a, b, c from test2 where a != 5;
select a, b, c from test2 where a < 4;
select a, b, c from test2 where a <= 2;
select a, b, c from test2 where a >= 7;
select a, b, c from test2 where a > 6;